### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by deepch** [ziutek/dvb#2]
Prompt your library can take h264 unit or stream or file and mux it ts file or ts http stream?
I can not find such examples

**Comment by ziutek** [comment]
This library handles TS packets and  can decode/encode sections to allow work with PSI tables.  There is no PES decoder/encoder yet because I don't need it currently. If I ever write one, there will be dvb/ts/pes package to import.

But you can write one yourself and share its code (simplified doc is here: https://en.wikipedia.org/wiki/Packetized_elementary_stream). PES handles H264 and any other streams that can be transported by MPEG-TS. Process of encoding/decoding PES packets is similar to encoding/decoding PSI sections (you need to find first TS packet that contains beginning of PES packet using pkt.PayloadUnitStart() method and handle payload of firs and subsequent packets until next packet with payload unit start indicator set. See psi.SectionDecoder and psi.SectionEncoder code.

**Comment by deepch** [comment]
Thank you for such a detailed reply . I'll try to do it.
